# Load Libraries

In [1]:
# import awswrangler as wr
import pandas as pd
# from credentials import AWS_PATH

In [29]:
# df = wr.s3.read_csv(AWS_PATH)
# df.head()

# Temporary file read, until we get AWS sorted out
df = pd.read_csv("data/nfl_sentiment_2025.csv")
df.head()

,player_id,player_name,player_first_name,player_last_name,player_position,team_abbreviation,game_id,bta_game_id,game_week,game_start_time,...,stats_receiving_rec_yards,stats_receiving_rec_td,stats_tackles_tackle_total,stats_tackles_sacks,stats_interceptions_interceptions,stats_interceptions_passes_defended,stats_fumbles_fum_forced,total_touches,total_opportunities,fantasy_points_ppr
0,6644.0,Charley Hughlett,Charley,Hughlett,LS,PHI,148741.0,2025.09.04.PHI.DAL,1.0,2025-09-05 00:20:00+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,7229.0,Dante Fowler,Dante,Fowler,DE,DAL,148741.0,2025.09.04.PHI.DAL,1.0,2025-09-05 00:20:00+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,7268.0,Bryan Anger,Bryan,Anger,P,DAL,148741.0,2025.09.04.PHI.DAL,1.0,2025-09-05 00:20:00+00,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,8047.0,Lane Johnson,Lane,Johnson,T,PHI,148741.0,2025.09.04.PHI.DAL,1.0,2025-09-05 00:20:00+00,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,8112.0,C.J. Goodwin,C.J.,Goodwin,CB,DAL,148741.0,2025.09.04.PHI.DAL,1.0,2025-09-05 00:20:00+00,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Data Cleaning and Validation

In [8]:
for col in df.columns:
    print(col + ": " + str(df[col].isnull().sum()))

player_id: 0
player_name: 0
player_first_name: 0
player_last_name: 0
player_position: 0
team_abbreviation: 0
game_id: 0
bta_game_id: 0
game_week: 0
game_start_time: 0
opp_offense_dvoa: 0
opp_defense_dvoa: 0
stats_snap_counts_offense_snaps: 0
stats_passing_pass_attempts: 11112
stats_passing_pass_completions: 11112
stats_passing_pass_yards: 11112
stats_passing_pass_td: 11112
stats_passing_pass_int: 11112
stats_passing_qb_rating: 11112
stats_rushing_rush_attempts: 10546
stats_rushing_rush_yards: 10546
stats_rushing_rush_td: 10546
stats_receiving_targets: 10546
stats_receiving_receptions: 10546
stats_receiving_rec_yards: 10546
stats_receiving_rec_td: 10546
stats_tackles_tackle_total: 0
stats_tackles_sacks: 0
stats_interceptions_interceptions: 0
stats_interceptions_passes_defended: 0
stats_fumbles_fum_forced: 0
total_touches: 0
total_opportunities: 0
fantasy_points_ppr: 0

In [15]:
# Check if nulls are in the same rows
print((df['stats_passing_pass_completions'].isnull() == df['stats_passing_pass_int'].isnull()).all())
print((df['stats_passing_pass_completions'].isnull() == df['stats_passing_pass_attempts'].isnull()).all())

print((df['stats_rushing_rush_yards'].isnull() == df['stats_receiving_rec_td'].isnull()).all())
print((df['stats_rushing_rush_yards'].isnull() == df['stats_rushing_rush_attempts'].isnull()).all())

True
True
True
True

In [ ]:
# Check positions of nulls
print(df[df['stats_passing_pass_completions'].isnull()]['player_position'].unique())
print(df[df['stats_rushing_rush_yards'].isnull()]['player_position'].unique())

# All of the nulls are linemen or defense, so this is expected

['LS' 'P' 'T' 'CB' 'K' 'FS' 'OT' 'OLB' 'ILB' 'G' 'C' 'NT' 'MLB' 'SS']
['P' 'T' 'CB' 'K' 'FS' 'OT' 'OLB' 'ILB' 'G' 'C' 'NT' 'MLB' 'SS']

## Fill NaNs with Zeroes

In [30]:
df.fillna(0, inplace=True)
df.head()

,player_id,player_name,player_first_name,player_last_name,player_position,team_abbreviation,game_id,bta_game_id,game_week,game_start_time,...,stats_receiving_rec_yards,stats_receiving_rec_td,stats_tackles_tackle_total,stats_tackles_sacks,stats_interceptions_interceptions,stats_interceptions_passes_defended,stats_fumbles_fum_forced,total_touches,total_opportunities,fantasy_points_ppr
0,6644.0,Charley Hughlett,Charley,Hughlett,LS,PHI,148741.0,2025.09.04.PHI.DAL,1.0,2025-09-05 00:20:00+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,7229.0,Dante Fowler,Dante,Fowler,DE,DAL,148741.0,2025.09.04.PHI.DAL,1.0,2025-09-05 00:20:00+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,7268.0,Bryan Anger,Bryan,Anger,P,DAL,148741.0,2025.09.04.PHI.DAL,1.0,2025-09-05 00:20:00+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,8047.0,Lane Johnson,Lane,Johnson,T,PHI,148741.0,2025.09.04.PHI.DAL,1.0,2025-09-05 00:20:00+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,8112.0,C.J. Goodwin,C.J.,Goodwin,CB,DAL,148741.0,2025.09.04.PHI.DAL,1.0,2025-09-05 00:20:00+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Check if columns are integers

In [43]:
numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns.tolist()
# print(numeric_cols)

int_inds = []

for col in numeric_cols:
    print(str(col) + ": " + str((df[col] % 1 == 0).all()))
    int_inds.append((df[col] % 1 == 0).all())

int_cols = [col for col, is_int in zip(numeric_cols, int_inds) if is_int]

player_id: True
game_id: True
game_week: True
opp_offense_dvoa: False
opp_defense_dvoa: False
stats_snap_counts_offense_snaps: True
stats_passing_pass_attempts: True
stats_passing_pass_completions: True
stats_passing_pass_yards: True
stats_passing_pass_td: True
stats_passing_pass_int: True
stats_passing_qb_rating: False
stats_rushing_rush_attempts: True
stats_rushing_rush_yards: True
stats_rushing_rush_td: True
stats_receiving_targets: True
stats_receiving_receptions: True
stats_receiving_rec_yards: True
stats_receiving_rec_td: True
stats_tackles_tackle_total: True
stats_tackles_sacks: False
stats_interceptions_interceptions: True
stats_interceptions_passes_defended: True
stats_fumbles_fum_forced: True
total_touches: True
total_opportunities: True
fantasy_points_ppr: False

In [44]:
# Convert appropriate columns to int64
for col in int_cols:
    df[col] = df[col].astype('int64')

## Verify values are positive

In [45]:
positive_cols = numeric_cols.copy()
positive_cols.remove('opp_offense_dvoa')
positive_cols.remove('opp_defense_dvoa')
positive_cols.remove('stats_passing_pass_yards')
positive_cols.remove('stats_rushing_rush_yards')
positive_cols.remove('stats_receiving_rec_yards')
positive_cols.remove('fantasy_points_ppr')


for col in positive_cols:
    print(str(col) + ": " + str((df[col] >= 0).all()))

player_id: True
game_id: True
game_week: True
stats_snap_counts_offense_snaps: True
stats_passing_pass_attempts: True
stats_passing_pass_completions: True
stats_passing_pass_td: True
stats_passing_pass_int: True
stats_passing_qb_rating: True
stats_rushing_rush_attempts: True
stats_rushing_rush_td: True
stats_receiving_targets: True
stats_receiving_receptions: True
stats_receiving_rec_td: True
stats_tackles_tackle_total: True
stats_tackles_sacks: True
stats_interceptions_interceptions: True
stats_interceptions_passes_defended: True
stats_fumbles_fum_forced: True
total_touches: True
total_opportunities: True

## Convert game start time to time objects

In [49]:
print(df['game_start_time'].dtype)
df['game_start_time'] = pd.to_datetime(df['game_start_time'])
print(df['game_start_time'].dtype)

object
datetime64[ns, UTC]

In [50]:
df.head()

,player_id,player_name,player_first_name,player_last_name,player_position,team_abbreviation,game_id,bta_game_id,game_week,game_start_time,...,stats_receiving_rec_yards,stats_receiving_rec_td,stats_tackles_tackle_total,stats_tackles_sacks,stats_interceptions_interceptions,stats_interceptions_passes_defended,stats_fumbles_fum_forced,total_touches,total_opportunities,fantasy_points_ppr
0,6644,Charley Hughlett,Charley,Hughlett,LS,PHI,148741,2025.09.04.PHI.DAL,1,2025-09-05 00:20:00+00:00,...,0,0,0,0.0,0,0,0,0,0,0.0
1,7229,Dante Fowler,Dante,Fowler,DE,DAL,148741,2025.09.04.PHI.DAL,1,2025-09-05 00:20:00+00:00,...,0,0,0,0.0,0,0,0,0,0,0.0
2,7268,Bryan Anger,Bryan,Anger,P,DAL,148741,2025.09.04.PHI.DAL,1,2025-09-05 00:20:00+00:00,...,0,0,0,0.0,0,0,0,0,0,0.0
3,8047,Lane Johnson,Lane,Johnson,T,PHI,148741,2025.09.04.PHI.DAL,1,2025-09-05 00:20:00+00:00,...,0,0,0,0.0,0,0,0,0,0,0.0
4,8112,C.J. Goodwin,C.J.,Goodwin,CB,DAL,148741,2025.09.04.PHI.DAL,1,2025-09-05 00:20:00+00:00,...,0,0,0,0.0,0,0,0,0,0,0.0

# Create Philadelphia Offense DataFrame

In [9]:
phi_off_df = df[df['team_abbreviation'] == 'PHI']
phi_off_df = phi_off_df[phi_off_df['player_position'].isin(['QB', 'RB', 'WR', 'TE'])]
phi_off_df.head()

,player_id,player_name,player_first_name,player_last_name,player_position,team_abbreviation,game_id,bta_game_id,game_week,game_start_time,...,stats_receiving_rec_yards,stats_receiving_rec_td,stats_tackles_tackle_total,stats_tackles_sacks,stats_interceptions_interceptions,stats_interceptions_passes_defended,stats_fumbles_fum_forced,total_touches,total_opportunities,fantasy_points_ppr
11,14493,Saquon Barkley,Saquon,Barkley,RB,PHI,148741,2025.09.04.PHI.DAL,1,2025-09-05 00:20:00+00,...,24.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0,23.0,18.40
12,14725,Dallas Goedert,Dallas,Goedert,TE,PHI,148741,2025.09.04.PHI.DAL,1,2025-09-05 00:20:00+00,...,44.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,7.0,11.40
19,16786,A.J. Brown,A.J.,Brown,WR,PHI,148741,2025.09.04.PHI.DAL,1,2025-09-05 00:20:00+00,...,8.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.80
24,18606,A.J. Dillon,A.J.,Dillon,RB,PHI,148741,2025.09.04.PHI.DAL,1,2025-09-05 00:20:00+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,3.0,1.00
28,18668,Jalen Hurts,Jalen,Hurts,QB,PHI,148741,2025.09.04.PHI.DAL,1,2025-09-05 00:20:00+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0,14.0,24.28

In [11]:
print(phi_off_df['player_name'].unique())

['Saquon Barkley' 'Dallas Goedert' 'A.J. Brown' 'A.J. Dillon'
 'Jalen Hurts' 'DeVonta Smith' 'Kylen Granson' 'Jahan Dotson'
 'John Metchie III' 'Grant Calcaterra' 'Will Shipley' 'Darius Cooper'
 'Tank Bigsby' 'Cameron Latu' 'E.J. Jenkins' 'Xavier Gipson'
 'Tanner McKee' 'Britain Covey']

In [12]:
print(df.columns.tolist())

['player_id', 'player_name', 'player_first_name', 'player_last_name', 'player_position', 'team_abbreviation', 'game_id', 'bta_game_id', 'game_week', 'game_start_time', 'opp_offense_dvoa', 'opp_defense_dvoa', 'stats_snap_counts_offense_snaps', 'stats_passing_pass_attempts', 'stats_passing_pass_completions', 'stats_passing_pass_yards', 'stats_passing_pass_td', 'stats_passing_pass_int', 'stats_passing_qb_rating', 'stats_rushing_rush_attempts', 'stats_rushing_rush_yards', 'stats_rushing_rush_td', 'stats_receiving_targets', 'stats_receiving_receptions', 'stats_receiving_rec_yards', 'stats_receiving_rec_td', 'stats_tackles_tackle_total', 'stats_tackles_sacks', 'stats_interceptions_interceptions', 'stats_interceptions_passes_defended', 'stats_fumbles_fum_forced', 'total_touches', 'total_opportunities', 'fantasy_points_ppr']

In [13]:
cols_to_keep = [
    'player_id',
    'player_name',
    'player_position',
    'game_id',
    'bta_game_id',
    'game_week',
    'opp_defense_dvoa',
    'stats_snap_counts_offense_snaps',
    'stats_passing_pass_attempts',
    'stats_passing_pass_completions',
    'stats_passing_pass_yards',
    'stats_passing_pass_td',
    'stats_passing_pass_int',
    'stats_passing_qb_rating',
    'stats_rushing_rush_attempts',
    'stats_rushing_rush_yards',
    'stats_rushing_rush_td',
    'stats_receiving_targets',
    'stats_receiving_receptions',
    'stats_receiving_rec_yards',
    'stats_receiving_rec_td'
]

phi_off_df = phi_off_df[cols_to_keep]
phi_off_df.head()

,player_id,player_name,player_position,game_id,bta_game_id,game_week,opp_defense_dvoa,stats_snap_counts_offense_snaps,stats_passing_pass_attempts,stats_passing_pass_completions,...,stats_passing_pass_td,stats_passing_pass_int,stats_passing_qb_rating,stats_rushing_rush_attempts,stats_rushing_rush_yards,stats_rushing_rush_td,stats_receiving_targets,stats_receiving_receptions,stats_receiving_rec_yards,stats_receiving_rec_td
11,14493,Saquon Barkley,RB,148741,2025.09.04.PHI.DAL,1,22.5,50.0,0.0,0.0,...,0.0,0.0,0.0,18.0,60.0,1.0,5.0,4.0,24.0,0.0
12,14725,Dallas Goedert,TE,148741,2025.09.04.PHI.DAL,1,22.5,52.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,7.0,7.0,44.0,0.0
19,16786,A.J. Brown,WR,148741,2025.09.04.PHI.DAL,1,22.5,55.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,8.0,0.0
24,18606,A.J. Dillon,RB,148741,2025.09.04.PHI.DAL,1,22.5,8.0,0.0,0.0,...,0.0,0.0,0.0,3.0,10.0,0.0,0.0,0.0,0.0,0.0
28,18668,Jalen Hurts,QB,148741,2025.09.04.PHI.DAL,1,22.5,63.0,23.0,19.0,...,0.0,0.0,94.2,14.0,62.0,2.0,0.0,0.0,0.0,0.0

In [14]:
int_cols = [
    'player_id',
    'game_id',
    'game_week',
    'stats_snap_counts_offense_snaps',
    'stats_passing_pass_attempts',
    'stats_passing_pass_completions',
    'stats_passing_pass_completions',
    'stats_passing_pass_yards',
    'stats_passing_pass_td',
    'stats_passing_pass_int',
    'stats_rushing_rush_attempts',
    'stats_rushing_rush_yards',
    'stats_rushing_rush_td',
    'stats_receiving_targets',
    'stats_receiving_receptions',
    'stats_receiving_rec_yards',
    'stats_receiving_rec_td'
]
for col in int_cols:
    phi_off_df[col] = phi_off_df[col].astype(int)

phi_off_df.head()

,player_id,player_name,player_position,game_id,bta_game_id,game_week,opp_defense_dvoa,stats_snap_counts_offense_snaps,stats_passing_pass_attempts,stats_passing_pass_completions,...,stats_passing_pass_td,stats_passing_pass_int,stats_passing_qb_rating,stats_rushing_rush_attempts,stats_rushing_rush_yards,stats_rushing_rush_td,stats_receiving_targets,stats_receiving_receptions,stats_receiving_rec_yards,stats_receiving_rec_td
11,14493,Saquon Barkley,RB,148741,2025.09.04.PHI.DAL,1,22.5,50,0,0,...,0,0,0.0,18,60,1,5,4,24,0
12,14725,Dallas Goedert,TE,148741,2025.09.04.PHI.DAL,1,22.5,52,0,0,...,0,0,0.0,0,0,0,7,7,44,0
19,16786,A.J. Brown,WR,148741,2025.09.04.PHI.DAL,1,22.5,55,0,0,...,0,0,0.0,0,0,0,1,1,8,0
24,18606,A.J. Dillon,RB,148741,2025.09.04.PHI.DAL,1,22.5,8,0,0,...,0,0,0.0,3,10,0,0,0,0,0
28,18668,Jalen Hurts,QB,148741,2025.09.04.PHI.DAL,1,22.5,63,23,19,...,0,0,94.2,14,62,2,0,0,0,0