# Load Libraries

In [ ]:
import awswrangler as wr
import pandas as pd
# from credentials import AWS_PATH

In [ ]:
# df = wr.s3.read_csv(AWS_PATH)
# df.head()

# Temporary file read, until we get AWS sorted out
df = pd.read_csv("data/nfl_sentiment_2025.csv")
df.head()

,player_id,player_name,player_first_name,player_last_name,player_position,team_abbreviation,game_id,bta_game_id,game_week,game_start_time,...,stats_receiving_rec_yards,stats_receiving_rec_td,stats_tackles_tackle_total,stats_tackles_sacks,stats_interceptions_interceptions,stats_interceptions_passes_defended,stats_fumbles_fum_forced,total_touches,total_opportunities,fantasy_points_ppr
0,6644.0,Charley Hughlett,Charley,Hughlett,LS,PHI,148741.0,2025.09.04.PHI.DAL,1.0,2025-09-05 00:20:00+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,7229.0,Dante Fowler,Dante,Fowler,DE,DAL,148741.0,2025.09.04.PHI.DAL,1.0,2025-09-05 00:20:00+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,7268.0,Bryan Anger,Bryan,Anger,P,DAL,148741.0,2025.09.04.PHI.DAL,1.0,2025-09-05 00:20:00+00,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,8047.0,Lane Johnson,Lane,Johnson,T,PHI,148741.0,2025.09.04.PHI.DAL,1.0,2025-09-05 00:20:00+00,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,8112.0,C.J. Goodwin,C.J.,Goodwin,CB,DAL,148741.0,2025.09.04.PHI.DAL,1.0,2025-09-05 00:20:00+00,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
phi_off_df = df[df['team_abbreviation'] == 'PHI']
phi_off_df = phi_off_df[phi_off_df['player_position'].isin(['QB', 'RB', 'WR', 'TE'])]
phi_off_df.head()

,player_id,player_name,player_first_name,player_last_name,player_position,team_abbreviation,game_id,bta_game_id,game_week,game_start_time,...,stats_receiving_rec_yards,stats_receiving_rec_td,stats_tackles_tackle_total,stats_tackles_sacks,stats_interceptions_interceptions,stats_interceptions_passes_defended,stats_fumbles_fum_forced,total_touches,total_opportunities,fantasy_points_ppr
11,14493,Saquon Barkley,Saquon,Barkley,RB,PHI,148741,2025.09.04.PHI.DAL,1,2025-09-05 00:20:00+00,...,24.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0,23.0,18.40
12,14725,Dallas Goedert,Dallas,Goedert,TE,PHI,148741,2025.09.04.PHI.DAL,1,2025-09-05 00:20:00+00,...,44.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,7.0,11.40
19,16786,A.J. Brown,A.J.,Brown,WR,PHI,148741,2025.09.04.PHI.DAL,1,2025-09-05 00:20:00+00,...,8.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.80
24,18606,A.J. Dillon,A.J.,Dillon,RB,PHI,148741,2025.09.04.PHI.DAL,1,2025-09-05 00:20:00+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,3.0,1.00
28,18668,Jalen Hurts,Jalen,Hurts,QB,PHI,148741,2025.09.04.PHI.DAL,1,2025-09-05 00:20:00+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0,14.0,24.28

In [11]:
print(phi_off_df['player_name'].unique())

['Saquon Barkley' 'Dallas Goedert' 'A.J. Brown' 'A.J. Dillon'
 'Jalen Hurts' 'DeVonta Smith' 'Kylen Granson' 'Jahan Dotson'
 'John Metchie III' 'Grant Calcaterra' 'Will Shipley' 'Darius Cooper'
 'Tank Bigsby' 'Cameron Latu' 'E.J. Jenkins' 'Xavier Gipson'
 'Tanner McKee' 'Britain Covey']

In [12]:
print(df.columns.tolist())

['player_id', 'player_name', 'player_first_name', 'player_last_name', 'player_position', 'team_abbreviation', 'game_id', 'bta_game_id', 'game_week', 'game_start_time', 'opp_offense_dvoa', 'opp_defense_dvoa', 'stats_snap_counts_offense_snaps', 'stats_passing_pass_attempts', 'stats_passing_pass_completions', 'stats_passing_pass_yards', 'stats_passing_pass_td', 'stats_passing_pass_int', 'stats_passing_qb_rating', 'stats_rushing_rush_attempts', 'stats_rushing_rush_yards', 'stats_rushing_rush_td', 'stats_receiving_targets', 'stats_receiving_receptions', 'stats_receiving_rec_yards', 'stats_receiving_rec_td', 'stats_tackles_tackle_total', 'stats_tackles_sacks', 'stats_interceptions_interceptions', 'stats_interceptions_passes_defended', 'stats_fumbles_fum_forced', 'total_touches', 'total_opportunities', 'fantasy_points_ppr']

In [13]:
cols_to_keep = [
    'player_id',
    'player_name',
    'player_position',
    'game_id',
    'bta_game_id',
    'game_week',
    'opp_defense_dvoa',
    'stats_snap_counts_offense_snaps',
    'stats_passing_pass_attempts',
    'stats_passing_pass_completions',
    'stats_passing_pass_yards',
    'stats_passing_pass_td',
    'stats_passing_pass_int',
    'stats_passing_qb_rating',
    'stats_rushing_rush_attempts',
    'stats_rushing_rush_yards',
    'stats_rushing_rush_td',
    'stats_receiving_targets',
    'stats_receiving_receptions',
    'stats_receiving_rec_yards',
    'stats_receiving_rec_td'
]

phi_off_df = phi_off_df[cols_to_keep]
phi_off_df.head()

,player_id,player_name,player_position,game_id,bta_game_id,game_week,opp_defense_dvoa,stats_snap_counts_offense_snaps,stats_passing_pass_attempts,stats_passing_pass_completions,...,stats_passing_pass_td,stats_passing_pass_int,stats_passing_qb_rating,stats_rushing_rush_attempts,stats_rushing_rush_yards,stats_rushing_rush_td,stats_receiving_targets,stats_receiving_receptions,stats_receiving_rec_yards,stats_receiving_rec_td
11,14493,Saquon Barkley,RB,148741,2025.09.04.PHI.DAL,1,22.5,50.0,0.0,0.0,...,0.0,0.0,0.0,18.0,60.0,1.0,5.0,4.0,24.0,0.0
12,14725,Dallas Goedert,TE,148741,2025.09.04.PHI.DAL,1,22.5,52.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,7.0,7.0,44.0,0.0
19,16786,A.J. Brown,WR,148741,2025.09.04.PHI.DAL,1,22.5,55.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,8.0,0.0
24,18606,A.J. Dillon,RB,148741,2025.09.04.PHI.DAL,1,22.5,8.0,0.0,0.0,...,0.0,0.0,0.0,3.0,10.0,0.0,0.0,0.0,0.0,0.0
28,18668,Jalen Hurts,QB,148741,2025.09.04.PHI.DAL,1,22.5,63.0,23.0,19.0,...,0.0,0.0,94.2,14.0,62.0,2.0,0.0,0.0,0.0,0.0

In [14]:
int_cols = [
    'player_id',
    'game_id',
    'game_week',
    'stats_snap_counts_offense_snaps',
    'stats_passing_pass_attempts',
    'stats_passing_pass_completions',
    'stats_passing_pass_completions',
    'stats_passing_pass_yards',
    'stats_passing_pass_td',
    'stats_passing_pass_int',
    'stats_rushing_rush_attempts',
    'stats_rushing_rush_yards',
    'stats_rushing_rush_td',
    'stats_receiving_targets',
    'stats_receiving_receptions',
    'stats_receiving_rec_yards',
    'stats_receiving_rec_td'
]
for col in int_cols:
    phi_off_df[col] = phi_off_df[col].astype(int)

phi_off_df.head()

,player_id,player_name,player_position,game_id,bta_game_id,game_week,opp_defense_dvoa,stats_snap_counts_offense_snaps,stats_passing_pass_attempts,stats_passing_pass_completions,...,stats_passing_pass_td,stats_passing_pass_int,stats_passing_qb_rating,stats_rushing_rush_attempts,stats_rushing_rush_yards,stats_rushing_rush_td,stats_receiving_targets,stats_receiving_receptions,stats_receiving_rec_yards,stats_receiving_rec_td
11,14493,Saquon Barkley,RB,148741,2025.09.04.PHI.DAL,1,22.5,50,0,0,...,0,0,0.0,18,60,1,5,4,24,0
12,14725,Dallas Goedert,TE,148741,2025.09.04.PHI.DAL,1,22.5,52,0,0,...,0,0,0.0,0,0,0,7,7,44,0
19,16786,A.J. Brown,WR,148741,2025.09.04.PHI.DAL,1,22.5,55,0,0,...,0,0,0.0,0,0,0,1,1,8,0
24,18606,A.J. Dillon,RB,148741,2025.09.04.PHI.DAL,1,22.5,8,0,0,...,0,0,0.0,3,10,0,0,0,0,0
28,18668,Jalen Hurts,QB,148741,2025.09.04.PHI.DAL,1,22.5,63,23,19,...,0,0,94.2,14,62,2,0,0,0,0